export type AwardsGalleryYear = string;

export type AwardsGalleryPhoto = {
  src: string;
  thumbnailSrc?: string;
  title: string;
  companyName: string;
  winnerCategory: string;
  year: AwardsGalleryYear;
  category: string;
  location: string;
  width: number;
  height: number;
};

export const DEFAULT_AWARDS_GALLERY_PHOTOS: AwardsGalleryPhoto[] = [
  {
    src: '/assets/images/banners/ts_winner_2026.jpg',
    title: 'Top Shop Winners Stage Reveal',
    companyName: 'Multiple Winner Companies',
    winnerCategory: 'Multiple Award Categories',
    year: '2026',
    category: 'Awards Ceremony',
    location: 'MRO Americas',
    width: 1920,
    height: 1080,
  },
  {
    src: '/assets/images/banners/ts_winner_2026_1.jpg',
    title: 'Winners Spotlight Moment',
    companyName: 'Multiple Winner Companies',
    winnerCategory: 'Multiple Award Categories',
    year: '2026',
    category: 'Awards Ceremony',
    location: 'MRO Americas',
    width: 1920,
    height: 1080,
  },
  {
    src: '/assets/images/ts_winner_2025/tag_aero.jpg',
    title: 'TAG Aero Team Recognition',
    companyName: 'TAG Aero, LLC',
    winnerCategory: 'Best APU Overhaul Repair',
    year: '2025',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2025/evans.jpg',
    title: 'Evans Composites Award Moment',
    companyName: 'Evans Composites, Inc.',
    winnerCategory: 'Best Plastic Components Repair',
    year: '2025',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2025/vse.jpg',
    title: 'VSE Aviation Winner Recognition',
    companyName: 'VSE Aviation Services - FL',
    winnerCategory: 'Best Accessories Class I, II, and III Repair',
    year: '2025',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2025/thales.jpg',
    title: 'Thales Avionics Team',
    companyName: 'Thales Avionics, Inc.',
    winnerCategory: 'Best In-Flight Entertainment Systems Repair',
    year: '2025',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2025/cima_aviation.jpg',
    title: 'CIMA Aviation Award Photo',
    companyName: 'CIMA Aviation',
    winnerCategory: 'Best Fuel Systems and Fuel Accessories Repair',
    year: '2025',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2025/crosscheck.jpg',
    title: 'Cross-Check Aviation Team',
    companyName: 'Cross-Check Aviation',
    winnerCategory: 'Best Avionics and Instruments Repair',
    year: '2025',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/group_photo_2024.jpeg',
    title: '2024 Winners Group Photo',
    companyName: 'Multiple Winner Companies',
    winnerCategory: 'Multiple Award Categories',
    year: '2024',
    category: 'Group Photo',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/ametek.jpg',
    title: 'Ametek Drake Air Recognition',
    companyName: 'Ametek MRO - Drake Air Tulsa',
    winnerCategory: 'Best Heat Transfer',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/aerostar.jpg',
    title: 'Aerostar Team Award',
    companyName: 'AeroStar, Inc.',
    winnerCategory: 'Best Pneumatics',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/avduct.jpg',
    title: 'AvDUCT Worldwide Winner',
    companyName: 'AvDUCT Worldwide',
    winnerCategory: 'Best Ducting',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/cima_aviation.jpg',
    title: 'CIMA Aviation Recognition',
    companyName: 'CIMA Aviation',
    winnerCategory: 'Best Fuel Systems and Fuel Accessories',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/delta.jpg',
    title: 'Delta TechOps Award Photo',
    companyName: 'Delta TechOps',
    winnerCategory: 'Best Total Solutions Provider',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/emc.jpg',
    title: 'EMC Aerospace Winner',
    companyName: 'EMC Aerospace, Inc.',
    winnerCategory: 'Best Accessories Class I, II, and III',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/hrd.jpg',
    title: 'HRD Aero Systems Recognition',
    companyName: 'HRD Aero Systems, Inc.',
    winnerCategory: 'Best Safety Equipment',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/icon_aero.jpg',
    title: 'Icon Aerospace Team',
    companyName: 'Icon Aerospace, LLC.',
    winnerCategory: 'Best Galley Components',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/luftansa.jpg',
    title: 'Lufthansa Technik Winner Photo',
    companyName: 'Lufthansa Technik',
    winnerCategory: 'Best Engine Components',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/setna.jpg',
    title: 'Setnix Team Recognition',
    companyName: 'Setnix LLC',
    winnerCategory: 'Best APU Components',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
  {
    src: '/assets/images/ts_winner_2024/summit.jpg',
    title: 'Summit Aerospace Award',
    companyName: 'Summit Aerospace, Inc.',
    winnerCategory: 'Best Landing Gear',
    year: '2024',
    category: 'Winner Presentation',
    location: 'MRO Americas',
    width: 1600,
    height: 1067,
  },
];
